### PR TITLE
navbar base code and little updates to css & html

### PR DESCRIPTION
**Pull request by lonewolfco**
- added in base navbar offcanvas code
- uploaded mushroom favicon
- cleared out css and inputed variables
- title icon and name
- changed header component folder name and functions to NavBar

### CODE REVIEW

**Review by lonewolfco — COMMENTED** [review]
No Merge Conflicts or anything major that would affect anyone else's work thus far 👍

**Comment by lonewolfco** [comment]
Added in another commit to this branch for navbar styling and animations :D 

- when you hover over dose, the text flips upside down
- when you hover over the links in the nav, the text changes color

**Comment by lonewolfco** [comment]
Screen Shot 2022-04-11 at 10 38 50 PM

Need to fix the login logout and mushroom image so it is on one row and flex, etc.

**Review by svellucci18 — APPROVED** [review]
Beautiful!

**Comment by svellucci18** [comment]
Looks good

**Pull request merged**
